### ISSUE TITLE
Some titles refuse to keep categories

### ISSUE THREAD

**Issue by thefunkygibbon** [Depressurizer/Depressurizer#139]
Ok so strictly i guess its not really an issue with depressurizer, but seeings as I don't see there being any place to discuss things (reddit/steam group) I'll try here.

I've got 3 titles in my steam library which seem to constantly lose their categories.
Tony Hawk's Pro Skater HD (yes it has been removed from the store, but i'm 100% i have other games which have too in my lib) 
Sam & Max 104: Abe Lincoln Must Die! (very oddly specific it is this 1 episode out of all of them)
Budget Cuts Demo (VR demo, I guess it could be relating to the fact its a demo?)

Any ideas?  Doesn't seem to matter if i add a cat via steam or depressurizer

**Comment by Theo47** [comment]
I can only try to take some shots in the dark.

Does it happen every time you restart steam or does it occur randomly?

Are you using steam from multiple computers (e.g your desktop and a laptop)? If you are, maybe try exiting steam on all of them first?

Maybe try switching to the beta version of steam? Or if you are already using the beta version, maybe switch back to the normal one?

Maybe check Steam\userdata\<number>\7\remote\sharedconfig.vdf  (open it with a text editor) and see if there is any difference between the entries for those 3 games and the rest?

If it happens when you add categories directly via steam, then it probably isn't caused by Depressurizer but by steam.

In that case, you may have better luck asking on the [steam reddit](https://www.reddit.com/r/Steam/) or the [steam group](https://steamcommunity.com/discussions/forum/1/).

**Comment by thefunkygibbon** [comment]
ok i did some more testing today, 
with tony hawks
yesterday I catted it.   i've restarted steam a few times since, it kept the cats correctly
just now i did a bit of an overhaul on my cats using new build of Depressurizer (bear in mind i did not touch either of the cats that I had added tony hawks to).  I open up steam, everything is fine and to be expected, all the massive changes have happened except tony hawks which has "defaulted" back to having no cats associated with it at all.
So now I am thinking that this problem may well have something to do with Depressurizer after all.

BTW I've tried all the things you suggested above, but the one where you suggested checking the contents of the vdf file... well i don't actually see the folder for the appid of the game ... as far as i can make out the game has the id of 207210 but i do not have that folder.
odd?

**Comment by Theo47** [comment]
The \<number\> on Steam\userdata\\<number\>\7\remote\sharedconfig.vdf is your steam id and not the appid. To be more precise it is the SteamID3 and you can find it using a tool like this: https://steamidfinder.com/

If it only happens with Depressurizer then it is a different issue though.

Can you check if those 3 titles appear inside Depressurizer?

Also go to Tools->Database Editor, uncheck "owned only", search for those 3 games and tell me what it says under "type".

Finally go to profile->edit profile->options and untick "remove entries for deleted or unknown games in steam configuration file". Check if it will now keep the categories.

p.s: Are you using the GameDB.xml.gz file that was included in last release or a different one?

**Comment by thefunkygibbon** [comment]
Ok, not sure why you suggested unchecking owned only as for some reason with those specific three games it thinks i don't own them.   all are classed as games in type.

Just done the unticking of remove entries as you suggested but also checked in the ignored tab and had 2 titles in there... one was tony hawks!  no idea how or why that got in there... unless there is an easy way to add it by accident?!  needless to say, i've removed that too.  will have another play around and see if it helps.   But still a bit odd that it seems to think i don't own it (and Sam & Max episode 104.)

**Comment by thefunkygibbon** [comment]
Ok so i just tried the quickest and easiest way i know to see if steam actually thinks i own the games (despite them being in my library)
http://compare2steam.com/?steamid=76561197967248430
searched for 
tony hawks pro skater hd
sam & max 103
sam & max 104
sam & max 105

(the other 103 and 105 episodes as a test to see if it picks them up correctly as there isnt any issue with them)

it says i own tony hawk, but 104 is saying i don't own it... very odd.   maybe 2 separate issues i'm seeing here..

also within depressurizer in my normal games list, i don't have tony or 104 so i can't auto cat them (maybe i've never been able to??)

**Comment by Theo47** [comment]
The "remove entries for deleted or unknown games in steam configuration file" setting basically (in an effort to clean up the file) removes categories for games in your ignored list, games with a type other than "game" or "application" in the database and games you don't own. So unticking it should stop the categories from getting removed.

Tony Hawks pro skater hd was in your ignore list so that explains why you couldn't see it. After removing it from the ignore list, you should be able to see it now inside depressurizer. You may need to restart depressurizer first before that happens though.
If you delete a game from the game list (e.g select it and press delete) it will also add it to the ignore list. I've already been told that this was unintuitive and there was a proposal to improve it (https://github.com/Depressurizer/Depressurizer/issues/128) which i plan to eventually implement.

As for sam & max 104, it is like you said. Steam says that you don't own it. If you check your profile (http://steamcommunity.com/id/thefunkygibbon/games/?tab=all) and search for "Sam & Max", you will see every episode from 101 to 305 except 104. I have no idea why steam would show all the other episodes and not that one.

**Comment by thefunkygibbon** [comment]
`

**Comment by thefunkygibbon** [comment]
Yeah, cool it seems to be ok now i restarted depressurizer. I see it and have categorized it ok. 
So as I suspected, Sam and max is a seperate oddity.  Guess i'll just leave it and see if Steam sorts itself out one day.  Might have a rummage through some other peoples games lists who also own Season 1 of S&M to see if they're missing it.  

Thanks anyway, great help.  User error 👍
