### ISSUE TITLE
End of an Era, new Road and Adjustments needed instead thanks to New Steam Library...

### ISSUE THREAD

**Issue by Black3ird** [Depressurizer/Depressurizer#172]
Dear Sir,

Thanks for all of your contributions to the project as Depressurizer _was_ quite useful in the _past_ and now half or more of its functions are "obsolete" thanks to Steam (Valve) integrated what once was only available via Depressurizer within their Internal Browser with the "New UI" so that Depressurizer is **not** needed anymore for the majority of the users (especially novice) as now Steam Client does it _"Better"_, don't shoot the messenger for saying the truth.

Why? One word as **"Dynamic Collections"** literally kills any need for Depressurizer as it's lightning fast compared to all the shenanigans Depressurizer using with constant "Needy" application to ever manualy updating the SharedConfig.vdf whereas new Steam Client does it On-the_Fly with unparalleled ease on user's end making your baby now halfway _defunct_. This is not a bad thing but a **PRAISE** to your application as Steam (Valve) recently also embedded half of functionality what _Augmented Steam_ offers (https://es.isthereanydeal.com/) which is merely used now for ITAD Price checking as half of its functions are either implemented within Steam Servers or at test phase like https://store.steampowered.com/labs/.

So what now? Simple as "Time for a Change" as it's _[Adapt or Die]_ situation at your hands for Depressurizer as Steam Library will also evolve taking more functionality from here. By functionality Depressurizer already lost these:
* Genre AutoCat
* Tags AutoCat
* Flags AutoCat (at least half of it)

because they were **"Internal"** to Steam Data as Steam Client now does it AUTO-matically without the need for manual Depressurizer Update Cycles thanks to _Dynamic Collections_. What's left for Depressurizer is all **"External"**(~ish to focus on) functions like:
* HowLong AutoCat
* User Score AutoCat (Steam now uses Meta Score but expected to support User Scores as well)
* Platform AutoCat (even if it's Internal Data, Steam doesn't care again _for now_ as VR has it)
* **Custom** AutoCats such as Publishers, Developers, Curators and Language...

And that's why Depressurizer Future lies within those functions Steam will _"Never"_ implement. And even if Depressurizer now has SAME functions for now Steam Client has, it's time to remove or "Update" them so that they'll create _Dynamic Collections_ instead of **Scraping** and doing manual labor for each entry which is _totally Inferior_ to Dynamic Collections. Humble suggestion is just to analyze current Steam Library actions over "Sharedconfig.vdf" (or other files involved) to **MiMic** _Dynamic Collections_ via Depressurizer Interface without actually scraping anything.

So instead of _lost functionality_, remove such defunct code to "Lighten" the application more (both in terms of Size and **Speed**) and focus on **Custom** Filters where Depressurizer is still providing `Unique Experience` compared to Steam Client will ever will. You can try to _"Resist"_ but this won't change the inevitable as Steam actions made _Discord_ take huge damage, (Enhanced) Augmented Steam lessened, Depressurizer being pushed away.

Why this plea? Simple as long time not used your baby after spending weeks on manual updates to get nearing _perfect_ arrangement on a thousands of games Steam library, and now decided to re-use Depressurizer to make "Final Changes" to updated Library to see `Depressurizer is what it always WAS, with its bugs and so forth` and it saddened me deeply. As a _Bug Report_, did you know that your Depressurizer-v4.12.1 **CAN'T** import thousands of games data whereas Depressurizer-v3.1.0 **DID** it without any complaints? Sorry to say but when did such _"Downgrade"_ began to happen even if _Changelog_ says otherwise?

And even sadder to see _both_ can't import data correctly so that even if Data is there within https://store.steampowered.com/api/appdetails/?appids=500 (For Example) Depressurizer **CAN'T** import Year AutoCat from whatever servers you're using as v4.12 got connected to a Akamai Node (which Steam uses) whereas  v3.1.0 got connected to [Elisa Oyj](https://whatismyipaddress.com/ip/193.229.113.138) (what?) Server for what purposes for same data with minutes apart of execution. All because just wanted to use "Year AutoCat" for later bought games where thousands of games fallen into `Unknown Text.`

Again, thanks for all of your hard work and contributions so far as this was an _Abandoned_ Project that you _Forked_ later merged (took over) with main as followed your progress through /r/Steam. Even if above has lots of criticism, it's form of _Tough Love_ as really don't want Depressurizer to become abandoned again in the light of Steam Library taking over your functionality. Just suggesting to **ADAPT** so that Depressurizer can be better than ever focusing and improving what's left instead of trying to compete with _"Dynamic Collections"_. Also even if Steam Client Library is a Web Script (so that it's Disabled with -no-browser switch unlike Old UI), it's _Faster_ than Depressurizer supposed to be an Executable needing .NET Framework.

It's still your choice but heed my warning...

Best Regards.

**Comment by kookyabird** [comment]
Sure the built-in features of Steam are pretty neat, and there's overlap with Depressurizer, but they're also missing too much for it to truly kill off this app. They have taken a huge step backwards when it comes to managing categories. You can't edit a games categories all at once anymore. Even if you switch to the small library mode, that doesn't carry over to the big mode. Do you know why? Because their small mode updates the same files from the old system that Depressurizer does, and the main library doesn't use those anymore. So Valve made a huge overhaul, and left the remains of the old system in place. And on top of that, when they brought back the small library feature, they did so in the laziest, most broken way.

And yeah dynamic collections are great, until you realize that the tagging and genres on Steam are horrible. Clustertruck is not an Adventure game. Ace Combat is not a Casual game. There's a mountain of games out there with mislabeled genres and tags. So I make a dynamic collection, and then have to spend a bunch of time removing dozens of games from it one at a time. Because there's no bulk editing anymore.

The new library is only an improvement over Depressurizer if you're willing to settle for the most bloated categories.

The only real problem right now is that the categories are handled elsewhere, and based on the behavior I've seen with the files in the old location I'm guessing it's primarily done in the cloud, which puts it out of reach of outside apps.

**Comment by dbacher** [comment]
Side note:
The new Steam library is pretty broken. Don't depend on it to show all your games (it often doesn't) or to even show any of your games at all (sometimes decides not to). In Valve's defense, I've been buying since the day Steam launched and so I might have a few more titles than the average Steam user.
But the new library just flat out doesn't let me get to any of my games some days, and so for the moment, depending on it is bad.  Valve seems to know that, I think that's why we got small library back because they know the new one is broken for large numbers of games and don't want to deal with it (which I think is also why it's using the old database format, etc. - I think it was a "wow, this is breaking for 900+ games in the list).
And so I went to run depressurizer and categorize the games.  Also, many even new titles pick up no categories at all, not even Genre, from whatever Valve is doing and so on a scale of 1 to 10 of reliability, I rate it -5.
Keep up the good work!

**Comment by kazerniel** [comment]
I've been trying to use Depressurizer to manually set year, userscore and HLTB categories to new games added to my Steam account, but it's becoming a major pain in the arse, as I have to do each operation twice, in both Depressurizer and Steam. The smaller mismatches and omissions between the two programs are already growing, and with 982 games and 165 categories in my library, I don't think this practice is sustainable on the long run.

I know that `resetcollections` command exists, but wouldn't it delete or mess up the new dynamic categories? How do others, who have tons of games and categories, deal with this issue?

Btw I sorely miss Depressurizer's advanced filters from the new Steam library. We can't even set an OR relationship between dynamic tags... (eg. label games tagged with either Comedy or Funny as Comedy in my Steam client)

**Comment by kookyabird** [comment]
Here's a fun fact I just discovered: The last patch that was made to the small library mode made it so Depressurizer works again! The trick is to exit Steam while it's in small library mode.

My best guess is the new library saves the config to the cloud. I've not found any data on my machine that changes for sure when a category change is made, aside from the old sharedconfig file, but that's only to support small library mode. When Steam starts up in small mode however, it does read in what is in the sharedconfig file. That means that as long as you're starting it up in small mode you'll pull in all of your category changes from Depressurizer.

Dynamic categories are not lost with this method either.

**Comment by kevyman** [comment]
The new Steam library has completely broken Depressurizer for me. 

I've done some research and it looks like sharedconfig.vdf (I think this is the file that depressurizer modifies) has no effect on the new steam collections, in that no changes to that file are reflected in steam.

As far as I can tell, I think appinfo.vdf is where the collections data is stored. That's as far as I've gotten. I'm not sure if Steam takes very kindly to modifying this file. 

So is that it, is Depressurizer officially dead now?

**Comment by ElTipejoLoco** [comment]
Can someone check if the issue is simply that Steam's new library is using new directories for some of the files Depressurizer reads from and writes to? I don't think it's appinfo.vdf, if only because that does not account for where it stores any non-Steam shortcuts' information.

Depressurizer continues to work with both the minigameslist and Big Picture Mode iterations of Steam's library, at least, as of me writing this. Modifying the categories via Depressurizer or either of the aforementioned two Steam library displays does not carry the changes over to the latest Steam library, and vice versa.

**Comment by ghost** [comment]
Steam doesn't use directories at all, but the Cloud, which is **unmodifiable.**

**Comment by kevyman** [comment]
So the new Steam Collections are stored in the cloud? That actually makes a lot of sense @LillieSatou, from what I was able to mess around with on my computer. How did you come across this information? I did a ton of googling about this a month ago and came up empty. 

If that's true, then it's confirmed that this project is dead. Sad day for us all.

**Comment by kazerniel** [comment]
Hmm, my new games are still getting added to `sharedconfig.vdf` by Steam. They even have my manual categories. Just not the dynamic ones.

**Comment by kookyabird** [comment]
@kazerniel What shows up in the sharedconfig.vdf file is more of a cache to support the Small Mode version of the library. I did a lot of testing and manual updating of that file and Steam wiped it out on launch most of the time. Also, a lot of times changes in the library didn't get reflected in there right away like they used to.

I have used every tool I know of for tracking the I/O activities of programs and have not been able to find a file stored locally that is consistently updated to reflect changes in the library. The only explanation is it's being stored somewhere not on our systems.

**Comment by Hezkezl** [comment]
For what it's worth, I was able to use this app to create a bunch of custom categories and have them work in Steam. You just have to run a command with Steam running to get it to update your collections.

I closed steam, saved the profile in Depressurizer, then re-opened Steam. Then I hit the Windows key + R (Or you can just type 'run' in the Start Menu and get the same popup, or right-click the Windows button icon in the lower-left of your screen and go to 'Run' to get it as well) then I typed in `steam://resetcollections` WITH STEAM OPEN to that, hit 'OK' and it asked me if I wanted to overwrite my categories with the ones I had created. I told it yes, and it did it. Now I've got all the genre/year/time-to-beat/score categories I had made in Pressurized, working in Steam :D 

So this app isn't really dead/not working, unless there's something else that I'm misreading about this thread.

EDIT: On a related note, the "Getting started" part of the Usage guide could use updating with that `steam://resetcollections` command. I had to google around and came across a thing on Reddit showing how to get it to work, so that info should be added here for ease of use. ([Reddit link here](https://old.reddit.com/r/Steam/comments/e7c0sv/best_way_to_organize_massive_steam_library_with/fajjhnn/) for confirmation)

**Comment by kazerniel** [comment]
But does it work with dynamic categories? For me that's the main question.

**Comment by Shea1550** [comment]
> I closed steam, saved the profile in Depressurizer, then re-opened Steam. Then I hit the Windows key + R,  then I typed in `steam://resetcollections` WITH STEAM OPEN to that, hit 'OK' and it asked me if I wanted to overwrite my categories with the ones I had created. I told it yes, and it did it.

This worked for me. Thanks so much!

**Comment by dbacher** [comment]
Good Old Games added Steam integration to their launcher (as well as PlayStation, Xbox, etc. integration).
Could be that since they like open source more than Valve does, that there's the potential that might be a route to improve the game library.  GOG's client can manage Valve, Epic, GOG and Ubi titles - there's an extension point there to integrate into additional services.  It can show Xbox and PlayStation titles, etc.
And so what I'm thinking is that might be a better option.

**Comment by Shea1550** [comment]
I'm chiming in again to say that `steam://resetcollections` no longer works for me, and my Uncategorized game list is growing. If anyone knows how to autocat with Steam, I'm very happy to hear it. Otherwise, I wish someone could get Depressurizer working again.

**Comment by kazerniel** [comment]
In the new Steam you can set up dynamic collections based on (multiple) tags, and some parameters such as unplayed/has achievements/multiplayer/etc. (+ you can add/remove games manually from these automated lists). You can run an advanced filter on top of the left sidebar, next to the search field, then save it as a dynamic collection.

The only major aspects missing from my current Steam category setup compared to Depressurizer is tagging review %, release year and HowLongToBeat times :/ And I wish Steam kept that popup window to add/remove multiple tags from a game, instead of having to do it one by one.

**Comment by Hezkezl** [comment]
> I'm chiming in again to say that `steam://resetcollections` no longer works for me, and my Uncategorized game list is growing. If anyone knows how to autocat with Steam, I'm very happy to hear it. Otherwise, I wish someone could get Depressurizer working again.

Did you make sure to run that command WITH STEAM OPEN AND RUNNING? Because you deal with Depressurizer while Steam's closed, but that resetcollections command is run with Steam open. I ask, because I literally just did it again about 30 seconds ago because of your comment (and I had some new games I bought that needed categorizing), and it worked just fine.

**Comment by Shea1550** [comment]
> > I'm chiming in again to say that `steam://resetcollections` no longer works for me, and my Uncategorized game list is growing. If anyone knows how to autocat with Steam, I'm very happy to hear it. Otherwise, I wish someone could get Depressurizer working again.
> 
> Did you make sure to run that command WITH STEAM OPEN AND RUNNING? Because you deal with Depressurizer while Steam's closed, but that resetcollections command is run with Steam open. I ask, because I literally just did it again about 30 seconds ago because of your comment (and I had some new games I bought that needed categorizing), and it worked just fine.

Yes, Steam is open and on the Library page. After running the command, I get the notification and select Confirm, but nothing happens. 

When opening Depressurizer, I get an error saying:

Error updating from local files:
Could not find a part of the path
'E:\Games\SteamLibrary\appcache\packageinfo.vdf'.

Could that be my problem?

**Comment by Shea1550** [comment]
> In the new Steam you can set up dynamic collections based on (multiple) tags, and some parameters such as unplayed/has achievements/multiplayer/etc. (+ you can add/remove games manually from these automated lists). You can run an advanced filter on top of the left sidebar, next to the search field, then save it as a dynamic collection.
> 
> The only major aspects missing from my current Steam category setup compared to Depressurizer is tagging review %, release year and HowLongToBeat times :/ And I wish Steam kept that popup window to add/remove multiple tags from a game, instead of having to do it one by one.

Thank you for that. I'm trying it now.

EDIT: I remember this now. I tried it when it first released but didn't use it because there are only a few categories. I might just have to suck it up, but I'd rather use Depressurizer if I can get it working. Thanks again!

**Comment by Hezkezl** [comment]
> 
> 
> > > I'm chiming in again to say that `steam://resetcollections` no longer works for me, and my Uncategorized game list is growing. If anyone knows how to autocat with Steam, I'm very happy to hear it. Otherwise, I wish someone could get Depressurizer working again.
> > 
> > 
> > Did you make sure to run that command WITH STEAM OPEN AND RUNNING? Because you deal with Depressurizer while Steam's closed, but that resetcollections command is run with Steam open. I ask, because I literally just did it again about 30 seconds ago because of your comment (and I had some new games I bought that needed categorizing), and it worked just fine.
> 
> Yes, Steam is open and on the Library page. After running the command, I get the notification and select Confirm, but nothing happens.
> 
> When opening Depressurizer, I get an error saying:
> 
> Error updating from local files:
> Could not find a part of the path
> 'E:\Games\SteamLibrary\appcache\packageinfo.vdf'.
> 
> Could that be my problem?

Most likely! I don't know what that error really means or how to fix it, but when I ran the command there was no error popping up for me...so with that being the only difference between our uses of the command, I can only assume that's the problem!

**Comment by Shea1550** [comment]
I've done a search for packageinfo.vdf and can't find anything that works. I even installed a program called SteamEdit in hope that it would create the file but no luck. If anyone knows how to fix this, I would very much appreciate it.

**Comment by Hezkezl** [comment]
> 
> 
> I've done a search for packageinfo.vdf and can't find anything that works. I even installed a program called SteamEdit in hope that it would create the file but no luck. If anyone knows how to fix this, I would very much appreciate it.

Only thing I've found for that file is something on the Steam forums for TF2 when someone mentioned that file was missing. They had to reinstall Steam to get it fixed. Make sure that, if you DO do that, to not delete your games otherwise you'll need to redownload all of them for the reinstall! https://steamcommunity.com/app/440/discussions/0/350541595110667715/ 

Hopefully reinstalling Steam will fix it for you :( If not then I've got no idea.

**Comment by Shea1550** [comment]
> > I've done a search for packageinfo.vdf and can't find anything that works. I even installed a program called SteamEdit in hope that it would create the file but no luck. If anyone knows how to fix this, I would very much appreciate it.
> 
> Only thing I've found for that file is something on the Steam forums for TF2 when someone mentioned that file was missing. They had to reinstall Steam to get it fixed. Make sure that, if you DO do that, to not delete your games otherwise you'll need to redownload all of them for the reinstall! https://steamcommunity.com/app/440/discussions/0/350541595110667715/
> 
> Hopefully reinstalling Steam will fix it for you :( If not then I've got no idea.

Well, thank you. I tried deleting all of the files inside the Steam folder and running the exe, but that didn't work. I've got, like, 4 TB worth of games downloaded, so I'm reluctant to try anything more drastic until I have time to move everything around. Thanks again for your help.
